apiVersion: v1
kind: Service
metadata:
  name: ums
  labels:
    run: ums
spec:
  clusterIP: None
  type: ClusterIP
  ports:
  - port: 5564
    name: websocket
    protocol: TCP
  selector:
    app: ums
---
kind: Service
apiVersion: v1
metadata:
  name: ums-external
spec:
  selector:
    app: ums
  ports:
  - protocol: TCP
    port: 5564
    targetPort: 5564
    name: websocket
  type: LoadBalancer
